### ISSUE TITLE
Plugin crashes on 2189

### ISSUE THREAD

**Issue by OfficerBozza** [pnwparksfan/rph-live-lights#6] opened 2020-12-20 03:20 UTC
**Describe the problem**
Plugin crashes when selecting any siren in the menu.

**To Reproduce**
1. Spawn any car
2. Open menu
3. Attempt to select any siren in the siren editor, or copy menu
4. Plugin crashes immediately

[RagePluginHook.log](https://github.com/pnwparksfan/rph-live-lights/files/5720447/RagePluginHook.log)

**System information (please complete the following information):**
 - Game version: 1.0.2189.0
 - RagePluginHook version: 1.83.1279.16081
 - Plugin version: 0.7 RC

**Comment by pnwparksfan** [comment] 2020-12-20 03:22
@OfficerBozza  this will be fixed when the next RagePluginHook update is released. There was a bug in `Entity.GetBoneOrientation` causing a memory access error. I can't do anything to fix this but I've tested a pre-release fix to RPH and confirmed the issue is resolved. That update should be public within a day or two.

**Closed by pnwparksfan** 2020-12-20 03:22 UTC
Labels: bug
